### ISSUE TITLE
troubles with pageflow-timeline-page and pageflow-react in pageflow 0.11.0

### ISSUE THREAD

**Issue by cschweingruber** [codevise/pageflow-timeline-page#2]
tried versions pageflow-react 0.1.0 and 0.1.1
(When i don't include pageflow-react in the Gemfile i get errors when initialiting pageflow-timeline-page plugin)

Now in preview and published pageflow i get:
Encountered error "ReferenceError: pageflow is not defined" when prerendering pageflow.timelinePage.Page with...

this comes from the line 
pageflow.timelinePage = pageflow.timelinePage || {}; 
in pageflow/timeline_page/components.js
i also tried the pending pull request...

in the editor the page is working fine

any hints? thanks in advance and greetings

**Comment by tf** [comment]
Hi cschweingruber,

can you show me the contents of your `app/assets/components.js` file? Regarding having to add `pageflow-react` to your `Gemfile`: that's strange. Maybe we are missing a require somewhere. Will check.

Tim

**Comment by cschweingruber** [comment]
Hi tf

you mean `app/assets/javascripts/components.js`?

there is only the line
`//= require "pageflow/timeline_page/components"`

**Comment by tf** [comment]
Yes. Can you add the following lines to the top of the `components.js` file:

```
//= require i18n
//= require i18n/translations

//= require pageflow/react/components
```
I realize now, that should either be included in `pageflow/timeline_page/components` or we will have to mention it in the readme.

**Comment by cschweingruber** [comment]
ok, thanks. I added these lines. but no difference:
```
React::ServerRendering::PrerenderError in Pageflow::Entries#show
Showing /home/yak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pageflow-react-0.1.1/app/views/pageflow/react/page.html.erb where line #2 raised:

Encountered error "ReferenceError: pageflow is not defined" when prerendering pageflow.timelinePage.Page with...
``` 
and

when i remove `pageflow-react` from Gemfile i get follwing error on startup:
```
15:03:23 scheduler.1 | rake aborted!
15:03:23 scheduler.1 | NameError: uninitialized constant Pageflow::React
15:03:23 scheduler.1 | /home/abc/pageflowapp/config/initializers/pageflow.rb:22:in `block in <top (required)>'
15:03:23 scheduler.1 | /home/abc/pageflowapp/config/initializers/pageflow.rb:117:in `<top (required)>'
15:03:23 scheduler.1 | /home/abc/pageflowapp/config/environment.rb:5:in `<top (required)>'
15:03:23 scheduler.1 | rake aborted!

```
line 22 is` config.plugin(Pageflow::TimelinePage.plugin)`

**Comment by tf** [comment]
The `Gemfile` problem is unrelated. I've created #4.

Did you restart the Rails server after changing `components.js`?

**Comment by robelix** [comment]
I think I'm stuck at the same problem:

```
ActionView::Template::Error (ReferenceError: pageflow is not defined):
    1: <% if page.template.present? %>
    2:   <% concat React::ServerRendering.render(
    3:      Pageflow.config.page_types.find_by_name!(page.template).component_name, sanitize_json(MultiJson.dump(
    4:      resolverSeed: @_pageflow_react_entry_seed ||= entry_seed(@entry),
    5:      pageId: page.perma_id
  (execjs):25:12663
  (execjs):32:14
  global ((execjs):1:102)
  Object.<anonymous> ((execjs):1:120)
  Module._compile (module.js:410:26)
  Object.Module._extensions..js (module.js:417:10)
  Module.load (module.js:344:32)
  Function.Module._load (module.js:301:12)
  Function.Module.runMain (module.js:442:10)
  startup (node.js:136:18)
  execjs (2.7.0) lib/execjs/external_runtime.rb:39:in `exec'
  execjs (2.7.0) lib/execjs/external_runtime.rb:14:in `initialize'
  execjs (2.7.0) lib/execjs/runtime.rb:57:in `new'
  execjs (2.7.0) lib/execjs/runtime.rb:57:in `compile'
  execjs (2.7.0) lib/execjs/module.rb:27:in `compile'
  react-rails (1.6.2) lib/react/server_rendering/exec_js_renderer.rb:10:in `initialize'
  react-rails (1.6.2) lib/react/server_rendering/sprockets_renderer.rb:25:in `initialize'
  react-rails (1.6.2) lib/react/server_rendering.rb:22:in `new'
  react-rails (1.6.2) lib/react/server_rendering.rb:22:in `create_renderer'
  react-rails (1.6.2) lib/react/server_rendering.rb:12:in `block in reset_pool'
[...]
```

**Comment by cschweingruber** [comment]
> The Gemfile problem is unrelated. I've created #4.
ok.

> Did you restart the Rails server after changing components.js?
sure! On question. The `app/assets/javascripts/components.js` has to be in my local fork of pageflow?

**Comment by tf** [comment]
No, there should be no need for a local fork. The `components.js` should be inside of the `app/assets/javascripts` directory of your Rails application (`pageflowapp` in your case, as I see from the stack traces above).

**Comment by robelix** [comment]
my app/assets/javascripts/components.js
currently is:
```
//= require i18n
//= require i18n/translations
//= require_tree ./components
//= require "pageflow/timeline_page/components"

```
already tried //= require_tree ./components at the beginning and at the end - doesn't change anything.

**Comment by cschweingruber** [comment]
ok. removed local fork
(had some troubles with `default.scss` in witch `@import "./default/base";` has to be replaced by `@import "pageflow/themes/default/default/base"`;

entries without pagetype pageflow-timeline-page are ok but with pageflow-timeline-page i get a new error:
```
ExecJS::ProgramError in Pageflow::Entries#show
Showing /home/yak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pageflow-react-0.1.1/app/views/pageflow/react/page.html.erb where line #2 raised:

TypeError: Cannot read property 'id' of undefined
Trace of template inclusion: /home/yak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pageflow-0.11.0/app/views/pageflow/pages/_page.html.erb, /home/yak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pageflow-0.11.0/app/views/pageflow/entries/_entry.html.erb, /home/yak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pageflow-0.11.0/app/views/pageflow/entries/show.html.erb
```

**Comment by tf** [comment]
@robelix `//= require_tree ./components` should not be necessary unless you have some custom components that you intend to use. Please, try to insert
```
//= require pageflow/react/components
```
before `//= require pageflow/timeline_page/components`.

@cschweingruber "default/default" seems wrong. Regarding the new error: Hard to say. Unfortunately `react-rails` does not give us a lot of debug info. Are there any errors in the console when opening or editing the entries inside the editor? Can you create a new entry with only a single empty timeline page and see if the problem still occurs.

**Comment by robelix** [comment]
Thank you!
adding //= require pageflow/react/components did it.

**Comment by cschweingruber** [comment]
sorry it is  `@import "pageflow/themes/default/base";` (in default.scss)
yes in the js-console there is the same error: Cannot read property 'id' of undefined
the code there is
```
	    key: '_getPage',
	    value: function _getPage() {
	      var _props$id$split = this.props.id.split(':');

thanks for today. I will investigate more tomorrow.
```

**Comment by tf** [comment]
Ok. Please paste the complete stack trace of the error that is displayed in the dev tools.

**Comment by cschweingruber** [comment]
```
Uncaught TypeError: Cannot read property 'id' of undefined_getPage 
@ react.self-902031c….js?body=1:7180_getPageLink @ react.self-902031c….js?body=1:7169perform 
@ react.self-902031c….js?body=1:7164exports.default @ react.self-902031c….js?body=1:7028(anonymous function) 
@ timeline_item_editor_menu.self-adf0867….js?…:125(anonymous function) 
@ timeline_item_editor_menu.self-adf0867….js?…:128
```

and

```
Uncaught TypeError: withPageLifecycle is not a function(anonymous function) 
@ timeline_item_spacer.self-868c1a8….js?body=1:118(anonymous function) 
@ timeline_item_spacer.self-868c1a8….js?body=1:123
```

**Comment by cschweingruber** [comment]
after reinstalling pageflow-timeline-page gem (i had a local fork too), everything is working!
thanks so much, have a good day!
Greetings Chrigu
