### ISSUE TITLE
mixin error

### ISSUE THREAD

**Issue by tirsteve** [codevise/pageflow-timeline-page#3]
Including this in app/assets/stylesheets/pageflow/themes/default.css.scss

@import "pageflow/timeline_page/themes/default";

rake assets:precompile give an error:

<pre>
rake aborted!
Sass::SyntaxError: Undefined mixin 'pageflow-page-type-pictograms'.
/www/pageflow/.rvm/gems/ruby-2.1.8/gems/pageflow-timeline-page-0.1.0/app/assets/stylesheets/pageflow/timeline_page/themes/default.scss:1:in `pageflow-page-type-pictograms'
/www/pageflow/.rvm/gems/ruby-2.1.8/gems/pageflow-timeline-page-0.1.0/app/assets/stylesheets/pageflow/timeline_page/themes/default.scss:1
</pre>

without the @import - all css is destroyed.

**Comment by tf** [comment]
Hi tirsteve,

please paste your `Gemfile.lock` and `pageflow/themes/default.scss` files into a gist and post a link.

**Comment by tirsteve** [comment]
Hi,

default.scss
`@import "./default/base";`

Gemfile.lock
`GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.6)
      actionpack (= 4.2.6)
      actionview (= 4.2.6)
      activejob (= 4.2.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.6)
      actionview (= 4.2.6)
      activesupport (= 4.2.6)                                                                                                                                                                                                                                            
      rack (~> 1.6)                                                                                                                                                                                                                                                      
      rack-test (~> 0.6.2)                                                                                                                                                                                                                                               
      rails-dom-testing (~> 1.0, >= 1.0.5)                                                                                                                                                                                                                               
      rails-html-sanitizer (~> 1.0, >= 1.0.2)                                                                                                                                                                                                                            
    actionview (4.2.6)                                                                                                                                                                                                                                                   
      activesupport (= 4.2.6)                                                                                                                                                                                                                                            
      builder (~> 3.1)                                                                                                                                                                                                                                                   
      erubis (~> 2.7.0)                                                                                                                                                                                                                                                  
      rails-dom-testing (~> 1.0, >= 1.0.5)                                                                                                                                                                                                                               
      rails-html-sanitizer (~> 1.0, >= 1.0.2)                                                                                                                                                                                                                            
    activeadmin (1.0.0.pre4)                                                                                                                                                                                                                                             
      arbre (~> 1.0, >= 1.0.2)                                                                                                                                                                                                                                           
      bourbon                                                                                                                                                                                                                                                            
      coffee-rails                                                                                                                                                                                                                                                       
      formtastic (~> 3.1)                                                                                                                                                                                                                                                
      formtastic_i18n                                                                                                                                                                                                                                                    
      inherited_resources (~> 1.6)                                                                                                                                                                                                                                       
      jquery-rails                                                                                                                                                                                                                                                       
      jquery-ui-rails                                                                                                                                                                                                                                                    
      kaminari (~> 0.15)                                                                                                                                                                                                                                                 
      rails (>= 3.2, < 5.1)                                                                                                                                                                                                                                              
      ransack (~> 1.3)                                                                                                                                                                                                                                                   
      sass-rails
      sprockets (< 4)
    activejob (4.2.6)
      activesupport (= 4.2.6)
      globalid (>= 0.3.0)
    activemodel (4.2.6)
      activesupport (= 4.2.6)
      builder (~> 3.1)
    activerecord (4.2.6)
      activemodel (= 4.2.6)
      activesupport (= 4.2.6)
      arel (~> 6.0)
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    ar_after_transaction (0.4.0)
      activerecord
    arbre (1.1.1)
      activesupport (>= 3.0.0)
    arel (6.0.3)
    aws-sdk (1.66.0)
      aws-sdk-v1 (= 1.66.0)
    aws-sdk-v1 (1.66.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    backbone-rails (1.0.0.1)
      rails (>= 3.0.0)
    bcrypt (3.1.11)
    bourbon (3.1.8)
      sass (>= 3.2.0)
      thor
    builder (3.2.2)
    cancancan (1.15.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.0.2)
    connection_pool (2.2.0)
    devise (3.5.10)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.9.0)
      devise (~> 3.2)
    ejs (1.1.1)
    erubis (2.7.0)
    execjs (2.7.0)
    formtastic (3.1.4)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.6.0)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    has_scope (0.6.0)
      actionpack (>= 3.2, < 5)
      activesupport (>= 3.2, < 5)
    htmlentities (4.3.4)
    http_accept_language (2.0.5)
    i18n (0.7.0)
    i18n-js (2.1.2)
      i18n
    inherited_resources (1.6.0)
      actionpack (>= 3.2, < 5)
      has_scope (~> 0.6.0.rc)
      railties (>= 3.2, < 5)
      responders
    jbuilder (2.6.0)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    jquery-fileupload-rails (0.4.1)
      actionpack (>= 3.1)
      railties (>= 3.1)
    jquery-layout-rails (0.1.0)
      jquery-rails
    jquery-rails (3.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kramdown (1.12.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    marionette-rails (1.1.0)
      rails (>= 3.1.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    mono_logger (1.1.0)
    multi_json (1.12.1)
    mysql2 (0.3.21)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    orm_adapter (0.5.0)
    pageflow (0.11.0)
      activeadmin (= 1.0.0.pre4)
      ar_after_transaction (~> 0.4.0)
      aws-sdk (~> 1.60)
      backbone-rails (~> 1.0.0)
      bcrypt (~> 3.1.7)
      bourbon (~> 3.1.8)
      cancancan (~> 1.10)
      devise (~> 3.5)
      devise-async (~> 0.9.0)
      ejs (~> 1.1)
      friendly_id (~> 5.0)
      htmlentities (~> 4.3)
      http_accept_language (~> 2.0)
      i18n-js (~> 2.1)
      jbuilder (>= 1.5, < 3.0)
      jquery-fileupload-rails (= 0.4.1)
      jquery-layout-rails (~> 0.1.0)
      jquery-rails (~> 3.0)
      jquery-ui-rails (= 5.0.5)
      kramdown (~> 1.5)
      marionette-rails (~> 1.1.0)
      pageflow-public-i18n (~> 1.2)
      paperclip (~> 4.2.4)
      rails (~> 4.2.6)
      redis (~> 3.0)
      redis-namespace (~> 1.5)
      resque (~> 1.25)
      resque-logger (~> 0.2.0)
      resque-scheduler (~> 2.5)
      resque_mailer (~> 2.2)
      sass (~> 3.4)
      sass-rails (~> 5.0)
      state_machine (~> 1.2)
      state_machine_job (~> 0.2.0)
      videojs_rails (= 4.1.0)
      wysihtml5x-rails (= 0.4.17)
      yajl-ruby (~> 1.2)
      zencoder (~> 2.5)
    pageflow-public-i18n (1.2.0)
    pageflow-react (0.1.1)
      multi_json (~> 1.11)
      pageflow (~> 0.10)
      react-rails (~> 1.6.0)
    pageflow-timeline-page (0.1.0)
      i18n-js
      pageflow (~> 0.10)
    paperclip (4.2.4)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
    pkg-config (1.1.7)
    polyamorous (1.3.1)
      activerecord (>= 3.0)
    rack (1.6.4)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.6)
      actionmailer (= 4.2.6)
      actionpack (= 4.2.6)
      actionview (= 4.2.6)
      activejob (= 4.2.6)
      activemodel (= 4.2.6)
      activerecord (= 4.2.6)
      activesupport (= 4.2.6)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.6)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (4.2.6)
      actionpack (= 4.2.6)
      activesupport (= 4.2.6)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (11.3.0)
    ransack (1.8.2)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.3)
    rdoc (4.2.2)
      json (~> 1.4)
    react-rails (1.6.2)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
    redis (3.0.7)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    resque (1.25.2)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
    `

**Comment by tf** [comment]
Did you insert `@import "pageflow/timeline_page/themes/default"` after `@import "./default/base"`? Can try use `@import "pageflow/themes/default/base"` (with the full path instead of the dot)? Should not really make difference, though.

**Comment by tirsteve** [comment]
no difference  :-(
rake assets:precompile breaks again..

**Comment by tf** [comment]
So what is the order of the two imports?

**Comment by tirsteve** [comment]
this order:

<pre>

@import "pageflow/themes/default/base"
@import "pageflow/timeline_page/themes/default";

</pre>

**Comment by tf** [comment]
That seems fine. Can you add the missing semicolon in the first line (if this is missing in your real file, too). Maybe this trips up the SCSS parser? Otherwise, not sure what could be wrong. We will have to investigate.

**Comment by tirsteve** [comment]
thanks - now this is done...now another error :-(

<pre>
ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):
   1: <% if page.template.present? %>
   2:   <% concat React::ServerRendering.render(
   3:      Pageflow.config.page_types.find_by_name!(page.template).component_name, sanitize_json(MultiJson.dump(
   4:      resolverSeed: @_pageflow_react_entry_seed ||= entry_seed(@entry),
   5:      pageId: page.perma_id
</pre>

But this is now a react error. should i open a new issue?

**Comment by tf** [comment]
That's a problem with `react-rails`, that I've also come across. Try adding the following line to `config/initializers/assets.rb`:
```
Rails.application.config.assets.precompile += %w(react-server.js components.js)
```
Please also have a look at #2, since, while unrelated to your current problem, some of the issues I am currently discussing there might also be relevant for you.
